// In google search as jenkins pipeline syntax --> pipeline syntax(jenkins) --> click on pipeline --> copy the code below this Declarative Pipeline fundamentals 
pipeline {
    agent { label 'AGENT-1' }
    environment { 
        PROJECT = 'EXPENSE'
        COMPONENT = 'BACKEND' 
        // DEPLOY_TO = 'QA'
        DEPLOY_TO = 'production'
    }
    options { 
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES') 
        // timeout(time: 5, unit: 'SECONDS')
        // In google search as colors in jenkins console output -->click on AnsiColor | Jenkins plugin
        ansiColor('xterm')
    } 
    parameters {
       choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    } 
    
    stages {
        stage('Init') {
            steps {
                script{
                    // copied from backend --> Jenkinfile --> stage('Docker Build')
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 70-ingress-alb
                        terraform init -reconfigure
                    """
                    // everytime we need to initialise terraform because we delete directory in    pipeline(we can see that command of deleting at post --> always --> deleteDir())
                    }
                }
            }
        }   
        stage('Apply or Destroy') {
            steps {
                script{
                    // copied from backend --> Jenkinfile --> stage('Docker Build')
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    if (params.ACTION == 'apply') {
                        sh """
                            cd 70-ingress-alb
                            terraform plan
                            terraform apply -auto-approve
                        """
                    } else {
                        sh """
                            cd 70-ingress-alb
                            terraform destroy -auto-approve
                        """
                    }
                    }
                }
            }
        }
        stage('Destroy Infra') {
            when { 
                expression { params.ACTION == 'destroy'}
            }
            steps {
                script{
                    // copied from backend --> Jenkinfile --> stage('Docker Build')
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    // for loop in groovy --> stack overflow
                    def list = ["60-acm", "50-ecr", "40-eks", "30-rds", "20-bastion", "10-sg", "00-vpc"]
                    for(item in list){
                        // each item taken into variable $item and destroyed
                        sh """
                            cd $item
                            terraform init -reconfigure
                            terraform destroy -auto-approve
                        """
                    }
                    }
                }
            }
        }
    }    
    //In google search as jenkins pipeline syntax --> pipeline syntax(jenkins) --> post
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir() // deletedir option post jenkins --> stack overflow
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }    
}