// In google search as jenkins pipeline syntax --> pipeline syntax(jenkins) --> click on pipeline --> copy the code below this Declarative Pipeline fundamentals 
pipeline {
    agent { label 'AGENT-1' }
    environment { 
        PROJECT = 'EXPENSE'
        COMPONENT = 'BACKEND' 
        // DEPLOY_TO = 'QA'
        DEPLOY_TO = 'production'
    }
    options { 
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES') 
        // timeout(time: 5, unit: 'SECONDS')
        // In google search as colors in jenkins console output -->click on AnsiColor | Jenkins plugin
        ansiColor('xterm')
    } 
    
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    } 
    
    stages {
        stage('Init') {
            steps {
                script{
                    // copied from backend --> Jenkinfile --> stage('Docker Build')
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 00-vpc
                        terraform init -reconfigure
                        terraform plan
                    """
                    // everytime we need to initialise terraform because we delete directory in    pipeline(we can see that command of deleting at post --> always --> deleteDir())
                    }
                }
            }
        }   
        stage('Apply') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps {
                script{
                    // copied from backend --> Jenkinfile --> stage('Docker Build')
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 00-vpc
                        terraform apply -auto-approve
                    """
                    }
                }
            }
        }
        stage('Trigger SG') {
            when { 
                expression { params.ACTION == 'apply'}
            }
            // In google search as "jenkins pipeline trigger downstream job" --> click on Metamorphant
            steps {
                build job: '10-sg', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
            // In google search as "jenkins pipeline trigger downstream job" --> click on Pipeline: Build Step
            // If propagate is false, then waits until 10-sg is success. We are keeping propagate is true because vpc is not responsibe for 10-sg is success or failure.     
            }
        }   
    }    
    //In google search as jenkins pipeline syntax --> pipeline syntax(jenkins) --> post
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir() // deletedir option post jenkins --> stack overflow
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }    
}