// In google search as jenkins pipeline syntax --> pipeline syntax(jenkins) --> click on pipeline --> copy the code below this Declarative Pipeline fundamentals 
pipeline {
    agent { label 'AGENT-1' }
    environment { 
        PROJECT = 'EXPENSE'
        COMPONENT = 'BACKEND' 
        // DEPLOY_TO = 'QA'
        DEPLOY_TO = 'production'
    }
    options { 
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES') 
        // timeout(time: 5, unit: 'SECONDS')
        // In google search as colors in jenkins console output -->click on AnsiColor | Jenkins plugin
        ansiColor('xterm')
    } 
    parameters {
       choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    } 
    
    stages {
        stage('Init') {
            steps {
                script{
                    // copied from backend --> Jenkinfile --> stage('Docker Build')
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan
                    """
                    // everytime we need to initialise terraform because we delete directory in    pipeline(we can see that command of deleting at post --> always --> deleteDir())
                    }
                }
            }
        }   
        stage('Apply') {
            // input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            // }
            steps {
                script{
                    // copied from backend --> Jenkinfile --> stage('Docker Build')
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        terraform apply -auto-approve
                    """
                    }
                }
            }
        }
       /*  stage('Parallel Stages') {
            // when ACTION is apply then triggers the below parallel things
            when { 
                expression { params.ACTION == 'apply'}
            }
            parallel {
                stage('20-bastion') {
                    steps {
                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('30-rds') {
                    steps {
                        build job: '30-rds', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('40-eks') {
                    steps {
                        build job: '40-eks', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('50-ecr') {
                    steps {
                        build job: '50-ecr', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }      
            }
        }
        // sequential stages jenkins ---> Pipeline Syntax --> Sequential Stages
        stage('Sequential') {
            stages {
                stage('60-acm') {
                    steps {
                        build job: '60-acm', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('70-ingress-alb') {
                    steps {
                        build job: '70-ingress-alb', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
            }
        }
    }     */
    //In google search as jenkins pipeline syntax --> pipeline syntax(jenkins) --> post
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir() // deletedir option post jenkins --> stack overflow
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }    
}